cart/urls.py
from django.urls import path

from .views import cart_detail_view, add_to_cart_view, remove_cart_view, clear_cart

app_name = 'cart'

urlpatterns = [
    path('', cart_detail_view, name='cart_detail'  ),
    path('add/<int:product_id>/', add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', remove_cart_view, name='cart_remove'),
    path('clear/', clear_cart, name='cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.conf import   settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls') ),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cart/forms.py
from django import forms

class AddToCartProductForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1,16)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)

    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)
    

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.contrib import messages

from products.models import Product
from .forms import AddToCartProductForm
from .cart import Cart 

def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item['product_update_quantity_form'] = AddToCartProductForm(initial={
            'quantity' : item['quantity'],
            'inplace' : True,
        })


    return render(request, 'cart/cart_detail.html',{
        'cart': cart,
    })

@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)
    form = AddToCartProductForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']
        cart.add(product, quantity, replace_current_quantity=cleaned_data['inplace'])

    return redirect('cart:cart_detail')


def remove_cart_view(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:cart_detail')

@require_POST
def clear_cart(request):
    cart = Cart(request)

    if len(cart):
        cart.clear()
        messages.success(request, 'All products successfully remmoved from your cart.')
    else:
        messages.success(request, 'your cart is already empty.')

    return redirect('product_list')

    

cart/templates/cart/cart_detail.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{% endblock title %}


{% block content %}

    {% include 'topheader.html' with header_name='Cart' %}

        <!-- Main Content Wrapper Start -->
        <div class="main-content-wrapper" dir="ltr">
            <div class="page-content-inner ptb--80">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 mb-md--50">
                           
                                <div class="row no-gutters">
                                    <div class="col-12">
                                        {% if cart %}
                                        <div class="table-content table-responsive">

                                            <table class="table text-center">
                                                <thead>
                                                    <tr>
                                                        <th>&nbsp;</th>
                                                        <th>picture</th> 
                                                        <th>name</th>
                                                        <th>price</th>
                                                        <th>number</th>
                                                        <th>total</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                  {% for item in cart %}
                                                  
                                                  <tr>
                                                    <td class="product-remove text-left"><a href="{% url 'cart:cart_remove' item.product_obj.id %}"><i class="flaticon flaticon-cross"></i></a></td>
                                                    
                                                    <td class="product-thumbnail text-left">
                                                        <img src="{{item.product_obj.cover.url}}">
                                                    </td>

                                                    <td class="product-name">
                                                        <h3>
                                                            <a href="{{item.product_obj.get_absolute_url}}">{{item.product_obj.title | truncatewords:2}}</a>
                                                        </h3>
                                                    </td>
                                                    <td class="product-price">
                                                        <span class="product-price-wrapper">
                                                            <span class="money">{{item.product_obj.price}}</span>
                                                        </span>
                                                    </td>
                                                    <td class="product-quantity">
                                                        <form class="d-flex" action="{% url 'cart:cart_add' item.product_obj.id %}" method="post">
                                                            {% csrf_token %}

                                                            <div class="quantity">
                                                                <input type="number" class="quantity-input" name="quantity" id="qty-1" value="{{item.quantity}}" min="1">
                                                            </div>
    
                                                                <button class="smal" type="submit"><i class="fa fa-refresh"></i></button>

                                                                {{item.product_update_quantity_form.inplace}}

                                                        </form>
                                                        
                                                    </td>
                                                    <td class="product-total-price">
                                                        <span class="product-price-wrapper">
                                                            <span class="money">{{item.total_price}}$</span>
                                                        </span>
                                                    </td>
                                                </tr>
                                                  
                                                  {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>  
                                        
                                        {% else %}

                                        <p>cart is Empty! please add some products to the cart</p>
                                        <p><a href="{% url 'product_list' %}">go shoping</a></p>
                                        {% endif %}
                                    </div>
                                </div>

                                {% if cart|length %}
                                    <div class="row no-gutters border-top pt--20 mt--20">
                                        <div class="col-sm-6 text-sm-right">
                                            <form action="{% url 'cart:cart_clear' %}" method="post">
                                                {% csrf_token %}
                                                <button type="submit" class="cart-form__btn">clear cart</button>
                                            </form>
                                        </div>
                                    </div> 
                                {% endif %}

                           
                        </div>
                        <div class="col-lg-4">
                            <div class="cart-collaterals">
                                <div class="cart-totals">
                                    <h5 class="font-size-14 font-bold mb--15">total</h5>
                                    <div class="cart-calculator">
                                        <div class="cart-calculator__item order-total">
                                            <div class="cart-calculator__item--head">
                                                <span>total </span>
                                            </div>
                                            <div class="cart-calculator__item--value">
                                                <span class="product-price-wrapper">
                                                    <span class="money">{{cart.get_total_price}}$</span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <a href="{% url 'order_created' %}" class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                                    checkout
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Content Wrapper Start -->

{% endblock content %}