cart/urls.py
from django.urls import path

from .views import cart_detail_view, add_to_cart_view, remove_cart_view, clear_cart

app_name = 'cart'

urlpatterns = [
    path('', cart_detail_view, name='cart_detail'  ),
    path('add/<int:product_id>/', add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', remove_cart_view, name='cart_remove'),
    path('clear/', clear_cart, name='cart_clear'),
]

config/urls.py
from django.contrib import admin
from django.conf import   settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls') ),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
    path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/_base.html
{% load static %}
<!doctype html>
<html  class="no-js" lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>{% block title %}        {% endblock title %}</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/icon.png' %}">

    <!-- ************************* CSS Files ************************* -->

    <link rel="stylesheet" href="{% static 'css/_base.css' %}">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">

    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">


</head>

<body dir='ltr'>

    <!-- Preloader Start -->
     <div class="ShoppingYar-preloader active">
        <div class="ShoppingYar-preloader-inner h-100 d-flex align-items-center justify-content-center">
            <div class="ShoppingYar-child ShoppingYar-bounce1"></div>
            <div class="ShoppingYar-child ShoppingYar-bounce2"></div>
            <div class="ShoppingYar-child zuka-bounce3"></div>
        </div>
    </div> 
    <!-- Preloader End -->

    <!-- Main Wrapper Start -->
    <div class="wrapper">

        <!-- Header Start -->
        <header class="header">
            <div class="header-inner fixed-header">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-9 col-lg-8 col-5 col-xs-0 col-none col-sm-block p-0">
                            <nav class="main-navigation">
                                <div class="site-branding" style="margin-right: 30px;">
                                    <a href="index.html" class="logo">
                                        <figure class="logo--normal d-none d-sm-block">
                                            <img class="px-5" src="..." style="max-height: 50px; margin-bottom: -15px;" alt="Logo">
                                        </figure>
                                    </a>
                                </div>
                                <div class="mainmenu-nav d-none d-lg-block w-100 pr-3">
                                    <ul class="mainmenu d-lg-flex jusity-content-end jusity-content-lg-start pt-4">
                                        <li class="mainmenu__item menu-item-has-children active">
                                            <a href="{% url 'home' %}" class="mainmenu__link">
                                                <span class="mm-text">Home</span>
                                            </a>
                                        </li>
                                        <li class="mainmenu__item menu-item-has-children">
                                            <a href="{% url 'product_list' %}" class="mainmenu__link">
                                                <span class="mm-text">productds</span>
                                            </a>
                                        </li>
                                        <li class="mainmenu__item menu-item-has-children">
                                            <a href="{% url 'about' %}" class="mainmenu__link">
                                                <span class="mm-text">About Us</span>
                                            </a>
                                         </li>
                                        <li class="mainmenu__item">
                                            <a href="contact-us.html" class="mainmenu__link">
                                                <span class="mm-text"> Contact Us </span>
                                            </a>
                                        </li>
                                        <li class="mainmenu__item menu-item-has-children">
                                            {% if user.is_authenticated %}
                                                <span>welcome {{user.username}}    |   <a href={% url 'account_logout' %}> logout </a></span>
                                            {% else %}
                                                <span><a href="{% url 'account_login' %}">login</a>   |   <a href="{% url 'account_signup' %}"> signup </a></span>
                                            {% endif %}
                                        </li>
                                    </ul>
                                </div>  
                            </nav>
                        </div>
                        <div class="col-xl-3 col-lg-4 col-sm-7 col-12 p-0">
                            <ul class="header-toolbar">
                                <li class="header-toolbar__item">
                                    <a href="wishlist.html" class="header-toolbar__btn mx-4">
                                        <i class="flaticon flaticon-like"></i>
                                    </a>
                                </li>
                                <li class="header-toolbar__item mini-cart-item">
                                    <a href="#miniCart" class="header-toolbar__btn toolbar-btn mini-cart-btn">
                                        <i class="flaticon flaticon-shopping-cart"></i>
                                        <sup class="mini-cart-count">{{cart|length}}</sup>
                                    </a>
                                </li>
                                <li class="header-toolbar__item user-info">
                                    <a href="my-account.html" class="header-toolbar__btn">
                                        <i class="flaticon flaticon-user"></i>
                                    </a>
                                    <ul class="user-info-menu">
                                        <li>
                                            <a class="text-right" href="my-account.html"> Profile </a>
                                        </li>
                                        <li>
                                            <a class="text-right" href="cart.html">Cart</a>
                                        </li>
                                        <li>
                                            <a class="text-right" href="wishlist.html">Favorites</a>
                                        </li>
                                        <li>
                                            <a class="text-right" href="order-tracking.html">Order History</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="header-toolbar__item">
                                    <a href="#searchForm" class="header-toolbar__btn toolbar-btn">
                                        <i class="flaticon flaticon-search"></i>
                                    </a>
                                </li>
                             
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="mobile-menu"></div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Header End -->



        {% if messages %}
            <div class="contaicer" dir="ltr">

                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} text-justify">{{message}}</div>
                    
                {% endfor %}

            </div>



        
        {% endif %}

        

{% block content %}

{% endblock content %}

    

        <!-- Footer Start-->
        <footer class="footer">
            <div class="footer-top bg-color ptb--50" data-bg-color="#f6f6f6">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-9 text-center">
                            <div class="footer-widget mb--50">
                                <div class="textwidget">
                                    <img src="..." alt="Logo">
                                </div>
                            </div>
                            <div class="footer-widget mb--50 pb--1">
                                <ul class="footer-menu">
                                    <li><a href="">About Us</a></li>
                                    <li><a href="">Trems and Condititons</a></li>
                                    <li><a href="">Contact Us</a></li>
                                </ul>
                            </div>
                            <div class="footer-widget">
                                mohammad partonia © | all rights reserved
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer End-->

        <!-- Search form Popup Start -->
        <div class="searchform__popup" id="searchForm">
            <a href="#" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
            <div class="searchform__body">
                <p>در باکس زیر عبارت خود را وارد کنید</p>
                <form class="searchform">
                    <input type="text" name="popup-search" id="popup-search" class="searchform__input" placeholder="جستجو در بین محصولات...">
                    <button type="submit" class="searchform__submit"><i class="flaticon flaticon-magnifying-glass-icon"></i></button>
                </form>
            </div>
        </div>
        <!-- Search form Popup End -->

        <!-- Mini Cart Start -->
        <aside class="mini-cart" id="miniCart">
            <div class="mini-cart-wrapper">
                <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
                <div class="mini-cart-inner">
                    <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">Cart</h3>
                    <div class="mini-cart__content">
                        <ul class="mini-cart__list text-right">
                            {% for item in cart %}
                            
                            <li class="mini-cart__product d-flex justify-content-between">
                                <div class="mini-cart__product__image">
                                    <a href="#">
                                        <img src="{% static 'img/products/prod-1-100x100.jpg' %}" alt="products">
                                    </a>
                                </div>
                                <div class="mini-cart__product__content pt-2">
                                    <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                        <a href="{{item.product_obj.get_absolute_url}}">{{item.product_obj.title | truncatewords:2}}</a>
                                        <a href="{% url 'cart:cart_remove' item.product_obj.id %}" class="">
                                            &#10060;
                                        </a>
                                    </span>
                                    <span class="mini-cart__product__quantity">
                                        <span>{{item.product_obj.price}}$ </span> &#215; <span>{{item.quantity}}</span>
                                    </span>
                                </div>
                            </li>
                            
                            {% endfor %}
                        </ul>
                        <div class="mini-cart__total">
                            <span>Total</span>
                            <span class="ammount">{{cart.get_total_price}}$</span>
                        </div>
                        <div class="mini-cart__buttons">
                            <a href="{% url 'cart:cart_detail' %}" class="btn btn-fullwidth btn-bg-sand mb--20">View Cart</a>
                            {% if cart|length %}
                                <a href="{% url 'order_created' %}" class="btn btn-fullwidth btn-bg-sand">Payment</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </aside>
        <!-- Mini Cart End -->

        <!-- Global Overlay Start -->
        <div class="ShoppingYar-global-overlay"></div>
        <!-- Global Overlay End -->

    </div>
    <!-- Main Wrapper End -->
 

    <!-- ************************* JS Files ************************* -->

    <!-- jQuery JS -->
    <script src="{% static 'js/vendor.js' %}"></script>

    <!-- Main JS -->
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/home.html
{% extends '_base.html' %}

{% block title %} home page {% endblock title %}

{% block content %}
home page



{% comment %} {%else%} {% endcomment %}
    {% comment %} <p><a href={% url 'login' %}>login</a> | <a href="{% url 'signup' %}">signup</a></p> {% endcomment %}
{% endblock content %}

templates/topheader.html
        <!-- Breadcrumb area Start -->
        <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                            <h1 class="page-title">{{header_name}}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Breadcrumb area End -->

templates/txt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>